- .github/workflows/codeql.yml
Analyze the Java. Make sure the Springs are good.
- Adds new "CodeQL" workflow to perform static analysis for PRs, pushes
to develop and main, and tags.
Closes #16.
> chore(cicd): Add workflow for static analysis with CodeQL

- src/main/java/com/mytiki/l0_auth/security/JWSBuilder.java
- src/main/java/com/mytiki/l0_auth/security/JWTConfig.java
- src/main/resources/application.properties
Adds support for scopes
- `registry`
- `registry:admin`
also adds:
- KID to JWTs
- Algorithm to JWKS
> Release: Adds l0-registry scopes

- pom.xml
- src/main/java/com/mytiki/l0_auth/features/latest/FeaturesConfig.java
- src/main/java/com/mytiki/l0_auth/features/latest/org_info/OrgInfoController.java
- src/main/java/com/mytiki/l0_auth/features/latest/org_info/OrgInfoService.java
- src/main/java/com/mytiki/l0_auth/features/latest/stripe/StripeConfig.java
- src/main/java/com/mytiki/l0_auth/features/latest/stripe/StripeController.java
- src/main/java/com/mytiki/l0_auth/features/latest/stripe/StripeService.java
- src/main/java/com/mytiki/l0_auth/security/SecurityConfig.java
- src/main/resources/application-dev.properties
- src/main/resources/application-prod.properties
- src/test/java/com/mytiki/l0_auth/StripeMock.java
- src/test/java/com/mytiki/l0_auth/StripeTest.java
- src/test/resources/application-ci.properties
uses checkout.session.completed event to set the org's billing id
closes #79
> feat: adds support for stripe webhooks

- openapi.yaml
- pom.xml
> Release: Add Orgs

- .gitmodules
- README.md
Moving to a single project for managing accounts (user, customer, and service), providing tokenized access and management. 
Folds in:
- console
- console-refresh
- idp
> feat: monorepo

- database/create_tables.sql
- src/main/java/com/mytiki/account/features/latest/FeaturesConfig.java
- src/main/java/com/mytiki/account/features/latest/addr_reg/AddrRegAOReq.java
- src/main/java/com/mytiki/account/features/latest/addr_reg/AddrRegAORsp.java
- src/main/java/com/mytiki/account/features/latest/addr_reg/AddrRegConfig.java
- src/main/java/com/mytiki/account/features/latest/addr_reg/AddrRegController.java
- src/main/java/com/mytiki/account/features/latest/addr_reg/AddrRegDO.java
- src/main/java/com/mytiki/account/features/latest/addr_reg/AddrRegRepository.java
- src/main/java/com/mytiki/account/features/latest/addr_reg/AddrRegService.java
- src/main/java/com/mytiki/account/features/latest/app_info/AppInfoService.java
- src/main/java/com/mytiki/account/utilities/B64Url.java
- src/main/java/com/mytiki/account/utilities/Constants.java
- src/main/java/com/mytiki/account/utilities/RSAFacade.java
- src/main/java/com/mytiki/account/utilities/SHA3Facade.java
- src/main/resources/application.properties
Roll features from registry service in
fixes #131
> Feat:add registry

- .github/workflows/tests.yml
- .github/workflows/update.yml
- infra/service/template.yml
- openapi.yaml
- pom.xml
- src/main/java/com/mytiki/account/features/latest/exchange/ExchangeConfig.java
- src/main/java/com/mytiki/account/features/latest/exchange/ExchangeService.java
- src/main/java/com/mytiki/account/features/latest/otp/OtpConfig.java
- src/main/java/com/mytiki/account/features/latest/otp/OtpService.java
- src/main/java/com/mytiki/account/features/latest/user_info/UserInfoService.java
- src/main/java/com/mytiki/account/utilities/UtilitiesConfig.java
- src/main/java/com/mytiki/account/utilities/builder/JwtBuilder.java
- src/main/java/com/mytiki/account/utilities/facade/ReadmeF.java
- src/main/resources/application-dev.properties
- src/main/resources/application-local.template.properties
- src/main/resources/application-prod.properties
- src/main/resources/application.properties
- src/test/java/com/mytiki/account/AddrRegTest.java
- src/test/java/com/mytiki/account/OrgInfoTest.java
> return readme_token on login

- database/create_tables.sql
- src/main/java/com/mytiki/account/features/latest/otp/OtpAOStartReq.java
- src/main/java/com/mytiki/account/features/latest/otp/OtpConfig.java
- src/main/java/com/mytiki/account/features/latest/otp/OtpDO.java
- src/main/java/com/mytiki/account/features/latest/otp/OtpService.java
- src/main/resources/application.properties
> fix: remove not anon from otp login

- infra/service/template.yml
- openapi.yaml
> fix: Secret Injection

- openapi.yaml
- pom.xml
redeploy to fix deployment issues.
> fix: version bump

- openapi.yaml
- pom.xml
- src/main/java/com/mytiki/account/features/latest/api_key/ApiKeyController.java
- src/main/java/com/mytiki/account/features/latest/api_key/ApiKeyService.java
- src/main/java/com/mytiki/account/utilities/facade/readme/ReadmeRsp.java
deploying to test integration options
> fix: trying out a diff key format for doc integration

- openapi.yaml
- pom.xml
- src/main/resources/public/assets/js/github.js
- src/main/resources/public/assets/js/google.js
- src/main/resources/public/assets/js/otp.js
> Release: deploy oauth fix

- src/main/resources/public/assets/js/github.js
- src/main/resources/public/assets/js/google.js
- src/main/resources/public/assets/js/otp.js
fix the url param, the case sensitive was crashing the request
> fix: google oauth url param

- openapi.yaml
- pom.xml
- src/main/java/com/mytiki/account/features/latest/oauth/OauthController.java
- src/main/java/com/mytiki/account/features/latest/oauth/OauthInternal.java
- src/main/java/com/mytiki/account/features/latest/ocean/OceanController.java
- src/main/resources/application.properties
none
adds a dummy api request for testing round trip with step functions.
> fix: add dummy api request

- infra/role/template.yml
> fix: update assume role policy

- openapi.yaml
- pom.xml
- src/main/java/com/mytiki/account/features/latest/cleanroom/CleanroomController.java
- src/main/java/com/mytiki/account/features/latest/cleanroom/CleanroomService.java
- src/test/java/com/mytiki/account/CleanroomTest.java
- src/test/java/com/mytiki/account/OceanTest.java
Fixes issue with oauth subjects when creating a new cleanroom.
> fix: issue with creating cleanrooms

- pom.xml
- src/main/java/com/mytiki/account/security/SecurityFilter.java
csrf cookies make rest apis difficult to work with.
> fix: remove csrf cookies

- openapi.yaml
- pom.xml
- src/main/java/com/mytiki/account/features/latest/subscription/SubscriptionService.java
create a new random subscription id on create
> fix: subscription id missing

- infra/service/template.yml
- openapi.yaml
- pom.xml
- src/main/java/com/mytiki/account/features/latest/ocean/OceanAOReq.java
- src/main/java/com/mytiki/account/features/latest/ocean/OceanService.java
fix: nullable results and s3 getObject permissions
> fix: nullable results and s3 getObject permissions

- database/create_tables.sql
- openapi.yaml
- pom.xml
- src/main/java/com/mytiki/account/features/latest/subscription/SubscriptionAO.java
- src/main/java/com/mytiki/account/features/latest/subscription/SubscriptionAOReq.java
- src/main/java/com/mytiki/account/features/latest/subscription/SubscriptionAORsp.java
- src/main/java/com/mytiki/account/features/latest/subscription/SubscriptionConfig.java
- src/main/java/com/mytiki/account/features/latest/subscription/SubscriptionController.java
- src/main/java/com/mytiki/account/features/latest/subscription/SubscriptionDO.java
- src/main/java/com/mytiki/account/features/latest/subscription/SubscriptionRepository.java
- src/main/java/com/mytiki/account/features/latest/subscription/SubscriptionService.java
- src/main/java/com/mytiki/account/features/latest/subscription/SubscriptionStatus.java
- src/main/resources/application.properties
- src/test/java/com/mytiki/account/OceanTest.java
> fix: ctas works

- openapi.yaml
- pom.xml
- src/main/java/com/mytiki/account/features/latest/cleanroom/CleanroomConfig.java
- src/main/java/com/mytiki/account/features/latest/cleanroom/CleanroomController.java
- src/main/java/com/mytiki/account/features/latest/cleanroom/CleanroomService.java
- src/main/java/com/mytiki/account/features/latest/ocean/OceanService.java
- src/main/java/com/mytiki/account/features/latest/provider/ProviderController.java
- src/main/java/com/mytiki/account/features/latest/provider_user/ProviderUserController.java
- src/main/java/com/mytiki/account/features/latest/subscription/SubscriptionController.java
- src/test/java/com/mytiki/account/CleanroomTest.java
- src/test/java/com/mytiki/account/OceanTest.java
Formatting and naming for integration with mytiki.com
> release: update oas docs

- openapi.yaml
- pom.xml
- src/main/java/com/mytiki/account/features/latest/cleanroom/CleanroomAOReq.java
- src/main/java/com/mytiki/account/features/latest/cleanroom/CleanroomService.java
Add descriptions for parameters
> Release: more docs fixes

- openapi.yaml
- pom.xml
- src/main/java/com/mytiki/account/features/latest/subscription/SubscriptionService.java
sanitize table names against `-`
> fix: temporary fix for dashes in table names

- openapi.yaml
- pom.xml
- src/main/java/com/mytiki/account/features/latest/ocean/OceanService.java
- count and sample queries are chained to the initial purchase subscription.
> fix: set subscription in chained req.

- src/main/resources/public/pages/code/github.html
- src/main/resources/public/pages/code/google.html
- src/main/resources/public/pages/login.html
- src/main/resources/public/pages/logout.html
> fix: loading in oauth and logout pages

- infra/service/template.yml
- openapi.yaml
- pom.xml
adds lake formation permission to task role
> fix: add lake formation permission

- infra/service/template.yml
- openapi.yaml
- pom.xml
redeploy with updated permissions.
> fix: add all of the missing lf permissions

- openapi.yaml
- pom.xml
- src/main/java/com/mytiki/account/features/latest/cleanroom/CleanroomController.java
- src/main/java/com/mytiki/account/features/latest/subscription/SubscriptionController.java
> fix: update api docs

- .github/workflows/codeql.yml
- .github/workflows/tests.yml
- openapi.yaml
- pom.xml
- src/main/java/com/mytiki/account/main/AppHandler.java
- src/main/resources/public/assets/styles/main.css
- tailwind/package-lock.json
- tailwind/package.json
relates to https://github.com/tiki/core/issues/14
- These error codes are required for use of event bridge destinations.
> Release: fix auth error

- openapi.yaml
- pom.xml
- src/main/java/com/mytiki/account/features/latest/ocean/OceanQuery.java
potentially fix bug with creating multiple tables in cleanroom
> fix: create tables in subfolders

- openapi.yaml
- pom.xml
- src/main/java/com/mytiki/account/features/latest/subscription/SubscriptionService.java
> Release: sanitization fixes

- openapi.yaml
- pom.xml
redeploy due to version bump failure.
> fix: force version bump.

- src/main/java/com/mytiki/account/features/latest/ocean/OceanLF.java
- tailwind/package-lock.json
- tailwind/package.json
Enable hybrid access mode for cleanrooms via lake formation. 
Required for integrations like snowflake.
> fix: always enable hybrid access mode

- openapi.yaml
- pom.xml
- src/main/java/com/mytiki/account/features/latest/oauth/OauthController.java
- src/main/java/com/mytiki/account/features/latest/oauth/OauthScopes.java
- src/main/java/com/mytiki/account/features/latest/provider_user/ProviderUserConfig.java
- src/main/java/com/mytiki/account/features/latest/provider_user/ProviderUserService.java
fixes filter function for non internal api scopes.
> fix: auth scopes for non-internal apis

- openapi.yaml
- pom.xml
- src/main/java/com/mytiki/account/features/latest/provider_user/ProviderUserController.java
- fix bug with missing RequestBody annotation.
> fix: user registration

- openapi.yaml
- pom.xml
- src/main/java/com/mytiki/account/features/latest/event/EventCallback.java
- src/main/resources/application.properties
> fix: callbacks to use event path

- openapi.yaml
- pom.xml
- src/main/java/com/mytiki/account/features/latest/event/EventService.java
- src/test/java/com/mytiki/account/EventTest.java
fix api req issue with subscription purchases
> fix: purchase subscription

- openapi.yaml
- pom.xml
- src/main/java/com/mytiki/account/features/latest/event/EventCallback.java
> fix: typo in callback url

- infra/service/template.yml
> fix: missing string sub.
